### PR TITLE
Wagtail 5.1 upgrade

### PR DESCRIPTION
**Pull request by katdom13**
Support ticket: https://torchbox.monday.com/boards/1124794299/pulses/1124795993

[Wagtail 5.1 release notes](https://docs.wagtail.org/en/stable/releases/5.1.html)

### Update wagtailfontawesomesvg icons following module update from ~0.0.4 to ~1.0.1
The newest version of `wagtailfontawesomesvg` (1.0.1) has had some icon design changes and icon renames since 0.0.4

https://github.com/wagtail-nest/wagtail-font-awesome-svg/tree/0.0.4/wagtailfontawesomesvg
https://github.com/wagtail-nest/wagtail-font-awesome-svg/tree/1.0.1/wagtailfontawesomesvg

### CODE REVIEW

**Comment by ibrahimawadhamid** [comment]
@katdom13 Is this PR ready?

**Comment by katdom13** [comment]
Hi @ibrahimawadhamid . Yes, it should be ready.

**Comment by ibrahimawadhamid** [comment]
@katdom13 what about this one #14 ?

**Comment by katdom13** [comment]
Closing in favor of: https://github.com/ibrahimawadhamid/wagtail_blocks/pull/15

**Pull request closed without merging**
